// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
"use-copy-to-clipboard": {
  name: "use-copy-to-clipboard",
  description: "",
  type: "registry:hook",
  registryDependencies: undefined,
  files: ["registry/hooks/use-copy-to-clipboard.ts"],
  component: React.lazy(() => import("@/registry/hooks/use-copy-to-clipboard.ts")),
  source: "",
  category: "",
  subcategory: "",
  chunks: []
},
"use-debounced-callback": {
  name: "use-debounced-callback",
  description: "",
  type: "registry:hook",
  registryDependencies: undefined,
  files: ["registry/hooks/use-debounced-callback.ts"],
  component: React.lazy(() => import("@/registry/hooks/use-debounced-callback.ts")),
  source: "",
  category: "",
  subcategory: "",
  chunks: []
},
"use-debounced-value": {
  name: "use-debounced-value",
  description: "",
  type: "registry:hook",
  registryDependencies: undefined,
  files: ["registry/hooks/use-debounced-value.ts"],
  component: React.lazy(() => import("@/registry/hooks/use-debounced-value.ts")),
  source: "",
  category: "",
  subcategory: "",
  chunks: []
},
"use-intersection-observer": {
  name: "use-intersection-observer",
  description: "",
  type: "registry:hook",
  registryDependencies: undefined,
  files: ["registry/hooks/use-intersection-observer.ts"],
  component: React.lazy(() => import("@/registry/hooks/use-intersection-observer.ts")),
  source: "",
  category: "",
  subcategory: "",
  chunks: []
},
"use-interval": {
  name: "use-interval",
  description: "",
  type: "registry:hook",
  registryDependencies: undefined,
  files: ["registry/hooks/use-interval.ts"],
  component: React.lazy(() => import("@/registry/hooks/use-interval.ts")),
  source: "",
  category: "",
  subcategory: "",
  chunks: []
},
"use-local-storage": {
  name: "use-local-storage",
  description: "",
  type: "registry:hook",
  registryDependencies: undefined,
  files: ["registry/hooks/use-local-storage.ts"],
  component: React.lazy(() => import("@/registry/hooks/use-local-storage.ts")),
  source: "",
  category: "",
  subcategory: "",
  chunks: []
},
"use-media-query": {
  name: "use-media-query",
  description: "",
  type: "registry:hook",
  registryDependencies: undefined,
  files: ["registry/hooks/use-media-query.ts"],
  component: React.lazy(() => import("@/registry/hooks/use-media-query.ts")),
  source: "",
  category: "",
  subcategory: "",
  chunks: []
},
"use-phoenix-channel": {
  name: "use-phoenix-channel",
  description: "",
  type: "registry:hook",
  registryDependencies: undefined,
  files: ["registry/hooks/use-phoenix-channel.ts"],
  component: React.lazy(() => import("@/registry/hooks/use-phoenix-channel.ts")),
  source: "",
  category: "",
  subcategory: "",
  chunks: []
},
"use-phoenix-socket": {
  name: "use-phoenix-socket",
  description: "",
  type: "registry:hook",
  registryDependencies: undefined,
  files: ["registry/hooks/use-phoenix-socket.ts"],
  component: React.lazy(() => import("@/registry/hooks/use-phoenix-socket.ts")),
  source: "",
  category: "",
  subcategory: "",
  chunks: []
},
}